                        <select class="form-control" name="codigo_cbo" id="design">
                         <option value="">...</option>
                            <option value="201115 Geneticista">201115 Geneticista</option>
                            <option value="203015 Pesquisador em Biologia de Micro-organismos e Parasitas">203015 Pesquisador em Biologia de Micro-organismos e Parasitas</option>
                            <option value="213150 Físico Médico">213150 Físico Médico</option>
                            <option value="221105 Biólogo">221105 Biólogo</option>
                            <option value="223204 Cirurgião Dentista - Auditor">223204 Cirurgião Dentista - Auditor</option>
                            <option value="AC">223208 Cirurgião Dentista - Clínico Geral</option>
                            <option value="223208 Cirurgião Dentista - Clínico Geral">223212 Cirurgião Dentista - Endodontista</option>
                            <option value="223216 Cirurgião Dentista - Epidemiologista">223216 Cirurgião Dentista - Epidemiologista</option>
                            <option value="223220 Cirurgião Dentista - Estomatologista">223220 Cirurgião Dentista - Estomatologista</option>
                            <option value="223224 Cirurgião Dentista - Implantodontista">223224 Cirurgião Dentista - Implantodontista</option>
                            <option value="223228 Cirurgião Dentista - Odontogeriatra">223228 Cirurgião Dentista - Odontogeriatra</option>
                            <option value="223232 Cirurgião Dentista - Odontologista Legal">223232 Cirurgião Dentista - Odontologista Legal</option>
                            <option value="223236 Cirurgião Dentista - Odontopediatra">223236 Cirurgião Dentista - Odontopediatra</option>
                            <option value="223240 Cirurgião Dentista - Ortopedista E Ortodontista">223240 Cirurgião Dentista - Ortopedista E Ortodontista</option>
                            <option value="223244 Cirurgião Dentista - Patologista Bucal">223244 Cirurgião Dentista - Patologista Bucal</option>
                            <option value="223248 Cirurgião Dentista - Periodontista">223248 Cirurgião Dentista - Periodontista</option>
                            <option value="223252 Cirurgião Dentista - Protesiólogo Bucomaxilofacial">223252 Cirurgião Dentista - Protesiólogo Bucomaxilofacial</option>
                            <option value="223256 Cirurgião Dentista - Protesista">223256 Cirurgião Dentista - Protesista</option>
                            <option value="223260 Cirurgião Dentista - Radiologista">223260 Cirurgião Dentista - Radiologista</option>
                            <option value="223264 Cirurgião Dentista - Reabilitador Oral">223264 Cirurgião Dentista - Reabilitador Oral</option>
                            <option value="223268 Cirurgião Dentista - Traumatologista Bucomaxilofacial">223268 Cirurgião Dentista - Traumatologista Bucomaxilofacial</option>
                            <option value="223272 Cirurgião Dentista de Saúde Coletiva">223272 Cirurgião Dentista de Saúde Coletiva</option>
                            <option value="223276 Cirurgião Dentista – Odontologia do Trabalho">223276 Cirurgião Dentista – Odontologia do Trabalho</option>
                            <option value="223280 Cirurgião Dentista - Dentística">223280 Cirurgião Dentista - Dentística</option>
                            <option value="223284 Cirurgião Dentista - Disfunção Temporomandibular e Dor Orofacial">223284 Cirurgião Dentista - Disfunção Temporomandibular e Dor Orofacial</option>
                            <option value="223288 Cirurgião Dentista - Odontologia para Pacientes com Necessidades Especiais">223288 Cirurgião Dentista - Odontologia para Pacientes com Necessidades Especiais</option>
                            <option value="223293 Cirurgião-Dentista da Estratégia de Saúde da Família">223293 Cirurgião-Dentista da Estratégia de Saúde da Família</option>
                            <option value="223505 Enfermeiro">223505 Enfermeiro</option>
                            <option value="223605 Fisioterapeuta Geral">223605 Fisioterapeuta Geral</option>
                            <option value="223710 Nutricionista">223710 Nutricionista</option>
                            <option value="223810 Fonoaudiólogo">223810 Fonoaudiólogo</option>
                            <option value="223905 Terapeuta Ocupacional">223905 Terapeuta Ocupacional</option>
                            <option value="223910 Ortoptista">223910 Ortoptista</option>
                            <option value="225103 Médico Infectologista">225103 Médico Infectologista</option>
                            <option value="225105 Médico Acupunturista">225105 Médico Acupunturista</option>
                            <option value="225106 Médico Legista">225106 Médico Legista</option>
                            <option value="225109 Médico Nefrologista">225109 Médico Nefrologista</option>
                            <option value="225110 Médico Alergista e Imunologista">225110 Médico Alergista e Imunologista</option>
                            <option value="225112 Médico Neurologista">225112 Médico Neurologista</option>
                            <option value="225115 Médico Angiologista">225115 Médico Angiologista</option>
                            <option value="225118 Médico Nutrologista">225118 Médico Nutrologista</option>
                            <option value="225120 Médico Cardiologista">225120 Médico Cardiologista</option>
                            <option value="225121 Médico Oncologista Clínico">225121 Médico Oncologista Clínico</option>
                            <option value="225122 Médico Cancerologista Pediátrico">225122 Médico Cancerologista Pediátrico</option>
                            <option value="225124 Médico Pediatra">225124 Médico Pediatra</option>
                            <option value="225125 Médico Clínico">225125 Médico Clínico</option>
                            <option value="225127 Médico Pneumologista">225127 Médico Pneumologista</option>
                            <option value="225130 Médico de Família e Comunidade">225130 Médico de Família e Comunidade</option>
                            <option value="225133 Médico Psiquiatra">225133 Médico Psiquiatra</option>
                            <option value="225135 Médico Dermatologista">225135 Médico Dermatologista</option>
                            <option value="225136 Médico Reumatologista">225136 Médico Reumatologista</option>
                            <option value="225139 Médico Sanitarista">225139 Médico Sanitarista</option>
                            <option value="225140 Médico do Trabalho">225140 Médico do Trabalho</option>
                            <option value="225142 Médico da Estratégia de Saúde da Família">225142 Médico da Estratégia de Saúde da Família</option>
                            <option value="225145 Médico em Medicina de Tráfego">225145 Médico em Medicina de Tráfego</option>
                            <option value="225148 Médico Anatomopatologista">225148 Médico Anatomopatologista</option>
                            <option value="225150 Médico em Medicina Intensiva">225150 Médico em Medicina Intensiva</option>
                            <option value="225151 Médico Anestesiologista">225151 Médico Anestesiologista</option>
                            <option value="225155 Médico Endocrinologista e Metabologista">225155 Médico Endocrinologista e Metabologista</option>
                            <option value="225160 Médico Fisiatra">225160 Médico Fisiatra</option>
                            <option value="225165 Médico Gastroenterologista">225165 Médico Gastroenterologista</option>
                            <option value="225170 Médico Generalista">225170 Médico Generalista</option>
                            <option value="225175 Médico Geneticista">225175 Médico Geneticista</option>
                            <option value="225180 Médico Geriatra">225180 Médico Geriatra</option>
                            <option value="225185 Médico Hematologista">225185 Médico Hematologista</option>
                            <option value="225195 Médico Homeopata">225195 Médico Homeopata</option>
                            <option value="225203 Médico em Cirurgia Vascular">225203 Médico em Cirurgia Vascular</option>
                            <option value="225210 Médico Cirurgião Cardiovascular">225210 Médico Cirurgião Cardiovascular</option>
                            <option value="225215 Médico Cirurgião de Cabeça e Pescoço">225215 Médico Cirurgião de Cabeça e Pescoço</option>
                            <option value="225220 Médico Cirurgião do Aparelho Digestivo">225220 Médico Cirurgião do Aparelho Digestivo</option>
                            <option value="225225 Médico Cirurgião Geral">225225 Médico Cirurgião Geral</option>
                            <option value="225230 Médico Cirurgião Pediátrico">225230 Médico Cirurgião Pediátrico</option>
                            <option value="225235 Médico Cirurgião Plástico">225235 Médico Cirurgião Plástico</option>
                            <option value="225240 Médico Cirurgião Torácico">225240 Médico Cirurgião Torácico</option>
                            <option value="225250 Médico Ginecologista e Obstetra">225250 Médico Ginecologista e Obstetra</option>
                            <option value="225255 Médico Mastologista">225255 Médico Mastologista</option>
                            <option value="225260 Médico Neurocirurgião">225260 Médico Neurocirurgião</option>
                            <option value="225265 Médico Oftalmologista">225265 Médico Oftalmologista</option>
                            <option value="225270 Médico Ortopedista e Traumatologista">225270 Médico Ortopedista e Traumatologista</option>
                            <option value="225275 Médico Otorrinolaringologista">225275 Médico Otorrinolaringologista</option>
                            <option value="225280 Médico Proctologista">225280 Médico Proctologista</option>
                            <option value="225285 Médico Urologista">225285 Médico Urologista</option>
                            <option value="225290 Médico Cancerologista Cirúrgico">225290 Médico Cancerologista Cirúrgico</option>
                            <option value="225295 Médico Cirurgião da Mão">225295 Médico Cirurgião da Mão</option>
                            <option value="225305 Médico Citopatologista">225305 Médico Citopatologista</option>
                            <option value="225310 Médico em Endoscopia">225310 Médico em Endoscopia</option>
                            <option value="225315 Médico em Medicina Nuclear">225315 Médico em Medicina Nuclear</option>
                            <option value="225320 Médico em Radiologia e Diagnóstico por Imagem">225320 Médico em Radiologia e Diagnóstico por Imagem </option>
                            <option value="225325 Médico Patologista">225325 Médico Patologista</option>
                            <option value="225330 Médico Radioterapeuta">225330 Médico Radioterapeuta</option>
                            <option value="225335 Médico Patologista Clínico / Medicina Laboratorial">225335 Médico Patologista Clínico / Medicina Laboratorial</option>
                            <option value="225340 Médico Hemoterapeuta">225340 Médico Hemoterapeuta</option>
                            <option value="225345 Médico Hiperbarista">225345 Médico Hiperbarista</option>
                            <option value="225350 Médico Neurofisiologista">225350 Médico Neurofisiologista</option>
                            <option value="2">239425 Psicopedagogo</option>
                            <option value="251510 Psicólogo Clínico">251510 Psicólogo Clínico</option>
                            <option value="251545 Neuropsicólogo">251545 Neuropsicólogo</option>
                            <option value="251550 Psicanalista">251550 Psicanalista</option>
                            <option value="251605 Assistente Social">251605 Assistente Social</option>
                            <option value="322205 Técnico de Enfermagem">322205 Técnico de Enfermagem</option>
                            <option value="322220 Técnico de Enfermagem Psiquiátrica">322220 Técnico de Enfermagem Psiquiátrica</option>
                            <option value="322225 Instrumentador Cirúrgico">322225 Instrumentador Cirúrgico</option>
                            <option value="322230 Auxiliar de Enfermagem">322230 Auxiliar de Enfermagem</option>
                            <option value="516210 Cuidador de Idosos">516210 Cuidador de Idosos</option>
                            <option value=">999999 CBO Desconhecido ou não Informado pelo Solicitante">999999 CBO Desconhecido ou não Informado pelo Solicitante</option>
                        </select>